[13.0][FIX] sale_order_move_menu_spil: missing dependencies
solvosci/slv-sale pull request #33
Opened 2022-07-12 12:51 UTC by ChristianSantamaria

Add invoice_line_ids.price_unit and quantity_done dependencies, update all stock move [('sale_line_id', '!=', False), ('state', '=', 'done')] with post-migration system

Need to install it in test, I will keep the status informed...

2022-07-12 17:01 UTC, dalonsod requested changes
See comments (minor changes)

2022-07-12 17:01 UTC, dalonsod commented on sale_order_move_menu_spil/__manifest__.py
> +    "version": "13.0.2.1.0",
This is a fix, so
```suggestion
    "version": "13.0.2.0.1",
```

2022-07-12 17:01 UTC, dalonsod commented on sale_order_move_menu_spil/migrations/13.0.2.1.0/post-migration.py
> +            record._compute_sale_move_menu()
Compute method is already multi, so you can simply use
```suggestion
        sale_move_ids._compute_sale_move_menu()            
```

2022-07-13 06:41 UTC, ChristianSantamaria commented
Done and tested 👍

2022-07-13 06:42 UTC, dalonsod approved these changes

2022-07-13 06:43 UTC, merged