[14.0][ADD] sale_order_engine_data
solvosci/slv-sale pull request #71
Opened 2024-07-30 07:57 UTC by IriaAlonso

Add new fields for engine data
@dalonsod

2024-07-30 09:00 UTC, dalonsod requested changes
See comments

2024-07-30 09:00 UTC, dalonsod commented on sale_order_engine_data/views/sale_order_views.xml
> +                <page name="engine data" string="Engine data">
Don't use name attributes with white spaces, replace them with underscores

2024-07-30 09:00 UTC, dalonsod commented on sale_order_engine_data/views/sale_order_views.xml
> +                    <group>
Could you provide a snapshot with this piece of form, so I can see final displayed width of this fields? If you look at other tabs, you'll probably find out that two group columns are rendered

2024-07-30 09:00 UTC, dalonsod commented on sale_order_engine_data/views/sale_order_views.xml
> +            </search>
This could probably work, but use a `<field name="xxx" position="after|berfore">` or `<xpath>` expression instead.

2024-07-30 09:00 UTC, dalonsod commented on sale_order_engine_data/views/sale_order_views.xml
> +            <xpath expr="//field[@name='partner_id']" position="after">
This only covers sales quotation tree. Look at Sales Order action, you'll see that another view is used there instead. Also add this field there.

2024-07-31 07:24 UTC, IriaAlonso commented
@dalonsod
![imagen](https://github.com/user-attachments/assets/bdfdab87-b852-48f0-ab12-5cf3451ece77)

2024-07-31 08:28 UTC, dalonsod commented
And in editable mode?

2024-07-31 08:29 UTC, IriaAlonso commented
![imagen](https://github.com/user-attachments/assets/6ba327b6-5c54-40d7-abd5-c8d55e740cc1)

2024-07-31 08:29 UTC, dalonsod commented
And please update PR title like this: "[14.0][ADD] sale_order_engine_data, sale_order_type_engine_data"

2024-07-31 08:36 UTC, dalonsod commented
OK, as you can see, fields width is too long. Please try to spliit it in two columns of fields, as others tabs do:

![imagen](https://github.com/user-attachments/assets/409da558-6c8f-4ef4-9859-9b276f0d2753)

2024-07-31 08:41 UTC, IriaAlonso commented
![imagen](https://github.com/user-attachments/assets/c2ed6598-4bd0-4cb9-939d-ba69a02cd919)

2024-07-31 11:26 UTC, dalonsod commented
Great!!

In the other hand, is `sale_order_type_engine_data` ready for review?

2024-07-31 11:34 UTC, IriaAlonso commented
> Great!!
> 
> In the other hand, is `sale_order_type_engine_data` ready for review?

yes :+1:

2024-07-31 11:49 UTC, dalonsod requested changes
See new comments related to `sale_order_type_engine_data`.

2024-07-31 11:49 UTC, dalonsod commented on sale_order_type_engine_data/views/sale_order_type_views.xml
> +                <filter name="engine_data_enabled" domain="[('engine_data_enabled','=',True)]"/>
For `filter` add a `string` attribute with the text that will be shown in Odoo,

2024-07-31 11:49 UTC, dalonsod commented on sale_order_type_engine_data/models/sale_order.py
> +    engine_hours = fields.Integer(string="Engine hours")
These fields are already defined in base addon `sale_order_engine_data`, so we shouldn't redefine again, unless they have to be changed (and it's not the case). So, remove them.

2024-07-31 11:53 UTC, IriaAlonso commented
@dalonsod changes done

2024-07-31 11:55 UTC, dalonsod commented
And one new requirement: could you add at sale_order_engine_data addon the new engine fields to quotation and sales order PDF report, when they have values?

They should be placed in SO header, like this:

![imagen](https://github.com/user-attachments/assets/7d622e5b-6e3f-4a20-855a-d28ec9ad469e)

2024-08-01 07:12 UTC, IriaAlonso commented
@dalonsod it is already done

2024-08-01 10:40 UTC, dalonsod requested changes
See comments, and when done, could you provide some screenshots?

2024-08-01 10:40 UTC, dalonsod commented on sale_order_engine_data/reports/sale_order_template.xml
> +    </template>
We only want to improve current sales quotation/sale order PDF report, not creating a new one, so we should remove this wrap template, that only is needed when we need to split a report in two different ones

2024-08-01 10:40 UTC, dalonsod commented on sale_order_engine_data/reports/sale_order_template.xml
> +            <div t-if="doc.engine_ref and doc.engine_hours" class="col-auto col-3 mw-100 mb-2" name="engine_data">
This block should be visible when one of the fields is filled, not both. With this code, if Engine Number is filled but hours net, Engine Number is not shown, and it's not the desired behavior. Please try this instead:
```suggestion
            <div t-if="doc.engine_ref or doc.engine_hours" class="col-auto col-3 mw-100 mb-2" name="engine_data">
```

2024-08-01 10:40 UTC, dalonsod commented on sale_order_engine_data/reports/sale_order_template.xml
> +                <span style="display: block">
Related to general <div> visibility criteria, for both <span> we should individually check their visibility, for example:
```suggestion
                <span t-if="doc.engine_ref" style="display: block">
```
Please change for both two fields

2024-08-01 10:51 UTC, IriaAlonso commented
When all fields are covererd:
![imagen](https://github.com/user-attachments/assets/5eab980e-44a4-4ebe-830c-2b9a5517edc2)
When one field is covered:
![imagen](https://github.com/user-attachments/assets/694e06f6-81f9-413b-b4f5-143385dd6070)

2024-08-01 11:35 UTC, dalonsod commented
LGTM :+1: 

I'll test it ASAP

2024-08-01 11:35 UTC, dalonsod commented
Then, please add translations for both addons

2024-08-01 12:14 UTC, IriaAlonso commented
> Then, please add translations for both addons

Done :+1:

2024-08-01 14:49 UTC, dalonsod commented
Once locally tested, changes have been made. @IriaAlonso please look at them.

<ins>Fixes</ins>
- Search for Engine eference was missing for sales order view (it was only added for sales quotation view).
- Engine reference was always required when a SO was confirmed, but we should exclude for this general case when order type doesn't require engine data.
- `README` info for `sale_order_type_engine_data` was incorrect, as was referring to `sale_order_engine_data` info.

<ins>Improvements</ins>
- Engine Data also added to Invoice report, when a SO with such data is linked to an invoice.

Could you update your development environment and test new changes?

2024-08-02 12:34 UTC, dalonsod commented
Installed in ArvTest environment and approved by customer :+1:

2024-08-02 12:35 UTC, merged