[17.0][MIG] sale_order_client_order_ref_mandatory
solvosci/slv-sale pull request #77
Opened 2024-10-09 08:55 UTC by IriaAlonso

2024-10-09 09:04 UTC, IriaAlonso commented
@dalonsod

2024-10-09 11:30 UTC, dalonsod requested changes
Tested, please take a look at tree views, because the field is duplicated (it seems that is added by default in v17).

2024-10-09 11:30 UTC, dalonsod commented on sale_order_client_order_ref_mandatory/static/description/index.html
> +<?xml version="1.0" encoding="utf-8"?>
Remove this line, as usual

2024-10-10 06:47 UTC, IriaAlonso commented
@dalonsod changes done

2024-10-10 07:17 UTC, IriaAlonso commented
@dalonsod done

2024-10-10 08:01 UTC, dalonsod approved these changes
:+1:

2024-10-10 08:01 UTC, merged

2024-10-10 08:01 UTC, dalonsod commented
@Anxo82 another finished migration