[17.0][ADD] sale_order_retrieve_customer_after_delivery
solvosci/slv-sale pull request #79
Opened 2024-10-18 11:44 UTC by IriaAlonso

- Move delivery address field to before customer field
- Delivery address field retrieve customer

2024-10-18 17:15 UTC, dalonsod commented
See my last commit:
* Passing context values across a compute field flow finally didn't work, so it wasn't an option.
* Indeed, adding an `onchange` method to a field that actually has a compute stored behavior (`partner_shipping_id`) didn't work. That's why partner shouldn't be filled when editing partner shipping address!
* So I've made a workaround with this approach: making a new instrumental `partner_shipping_2_id` field, the visible one, with almost the same definition than original one, that makes the magic of autofilling partner. And a last step: overwrite compute original partner shipping method, making new and old field identical (former `partner_shipping_id` is stored in background, because we need it for other processes!).

Please check that it's working, and:
* Add a pre-init hook that create basic `partner_shipping_2_id` field and initialize it with `partner_shipping_id` content. If you don't find a similiar example, please ask.
* Make translations and `README` stuff.

2024-10-22 06:42 UTC, IriaAlonso commented
@dalonsod

2024-10-22 18:01 UTC, dalonsod requested changes
See comments, and also:
* `i18n` folder is wrongly placed, move it to addon root. If not, translations should never be applied.
* Add a `ROADMAP.rst` file indicating that is pending compatibility with non-delivery address mode (something stupid, installing this addon and disabling delivery address mode, but possible). Then, re-create `README.rst`.

We'll keep name's addon at this point, it's not a very good mane IMO but not terrible anyway 😉

cc @ChristianSantamaria

2024-10-22 18:01 UTC, dalonsod commented on sale_order_retrieve_customer_after_delivery/__init__.py
> +        create_column(env.cr, "sale_order", "partner_shipping_2_id", "character varying")
This is wrong, `partner_shipping_2_id` should be an `integer` value, as a `Many2one` field:
```suggestion
        create_column(env.cr, "sale_order", "partner_shipping_2_id", "integer")
```

2024-10-22 18:01 UTC, dalonsod commented on sale_order_retrieve_customer_after_delivery/__init__.py
> +def pre_init_hook(env):
This function should be better placed in a `hooks.py` file at this level and then import it in `__init__.py` with 

`from .hooks import pre_init_hook`

See e.g. https://github.com/OCA/product-attribute/tree/17.0/product_logistics_uom

2024-10-22 18:01 UTC, dalonsod commented on sale_order_retrieve_customer_after_delivery/static/description/index.html
> +<?xml version="1.0" encoding="utf-8"?>
Remove this as usual in v17

2024-10-23 06:30 UTC, IriaAlonso commented
@dalonsod

2024-10-23 06:42 UTC, dalonsod requested changes
See very minor comment, and I'll test It ASAP

2024-10-23 06:42 UTC, dalonsod commented on sale_order_retrieve_customer_after_delivery/i18n/es.po
> +msgstr "Dirección de entrega"
Better this (this label is only for field definition, so we've interested in marking it different than original one)

```suggestion
msgstr "Dirección de entrega (nueva)"
```

2024-10-23 06:46 UTC, IriaAlonso commented
@dalonsod done

2024-10-23 09:42 UTC, dalonsod commented
Squash made with latest change:

![imagen](https://github.com/user-attachments/assets/3b8470f2-e9b8-4f4d-ab55-6152ae32499d)

This typo in view was due to a `replace` instead of `attributes` in `xpath` for `form` view, when hiding original delivery address field. Fixed.

2024-10-23 09:43 UTC, merged

2024-10-23 09:44 UTC, dalonsod commented
@ChristianSantamaria could you install it at v17 CmhProd environment and make it also available for CmhTest environment?