[17.0][ADD] sale_order_partner_invoice_period
solvosci/slv-sale pull request #83
Opened 2024-11-19 08:49 UTC by DantePereyra

Adds a selector of period to invoice directions.

2024-11-19 08:59 UTC, dalonsod requested changes
See comment, and also add pending requirements:
* For sales orders tree view, the field must be added, as optional and shown by default.
* For sales orders search view, we should be able to group by this new field.

2024-11-19 08:59 UTC, dalonsod commented on sale_order_partner_invoice_period/models/res_partner.py
> +    period=fields.Selection(
We should better define this field using a more specific name, like e.g.
```suggestion
    invoice_period = fields.Selection(
```

2024-11-19 12:58 UTC, DantePereyra commented
Changes done.

2024-11-19 17:41 UTC, dalonsod requested changes
See comments

2024-11-19 17:41 UTC, dalonsod commented on sale_order_partner_invoice_period/views/sale_order_view.xml
> +    <record id="view_order_form_inherit" model="ir.ui.view">
Don't change XML ID from original, better preserve this:
```suggestion
    <record id="view_order_form" model="ir.ui.view">
```
This view will be actually fully named by Odoo as `sale_order_partner_invoice_period.view_order_form`, so its ID is truly unique, and in this way is simpler to find.

2024-11-19 17:41 UTC, dalonsod commented on sale_order_partner_invoice_period/views/sale_order_view.xml
> +    <record id="view_sales_order_filter_inherit" model="ir.ui.view">
The same as above

2024-11-19 17:41 UTC, dalonsod commented on sale_order_partner_invoice_period/views/res_partner_view.xml
> +        <field name="name">res.partner.view.form.inherit</field>
Preserve the same name as original view and add ` (in sale_order_partner_invoice_period)` , so inspecting name we can figure out its origin.

2024-11-19 17:41 UTC, dalonsod commented on sale_order_partner_invoice_period/views/sale_order_view.xml
> +        <field name="name">sale.order.searh.inherit</field>
Seems to be a typo here

2024-11-19 17:41 UTC, dalonsod commented on sale_order_partner_invoice_period/views/sale_order_view.xml
> +            <xpath expr="//search" position="inside">
Don't use inside, because its final position becomes very undeterminated. Better find an existing field/filter for every element to be added.

2024-11-19 17:41 UTC, dalonsod commented on sale_order_partner_invoice_period/views/sale_order_view.xml
> +                <field name="partner_invoice_period"/>
Does this search field work? We don't need it, we only need grouping by it

2024-11-19 17:41 UTC, dalonsod commented on sale_order_partner_invoice_period/views/sale_order_view.xml
> +    <record id="sale_order_tree_inherit" model="ir.ui.view">
The same as above

2024-11-20 08:14 UTC, DantePereyra commented
Changes done.

2024-11-20 08:37 UTC, dalonsod commented
:+1: please add README stuff and I'll test it

2024-11-20 08:51 UTC, DantePereyra commented
Done!

2024-11-20 11:28 UTC, dalonsod commented
@DantePereyra during installation this error is raised:

```
odoo.tools.convert.ParseError: while parsing /home/david/Solvos/Desarrollo/CodeProjects/odoo-17-oca/slv-sale/sale_order_partner_invoice_period/views/sale_order_view.xml:16
Invalid Expression while parsing xpath "//search//filter[@name='order_month'"

View error context:
'-no context-'
```

Could you check?

2024-11-20 11:45 UTC, DantePereyra commented
Done, it was an end bracket missing. It must work perfect now.

2024-11-20 12:13 UTC, dalonsod requested changes
Make these four new tasks:
- Make `invoice_period` only available for sales orders tree view, not for quotations. If you inherit from `sale.view_order_tree` instead of `sale.sale_order_tree` (base view for both quotations and orders) you'll achieve the desired behavior.
- Place new field in tree view after `invoice_status`, that is a better location.
- Use `widget="badge"` for this field, as `invoice_status` does.
- Add default and `es` translations.

2024-11-20 15:09 UTC, DantePereyra commented
All done.

2024-11-20 15:27 UTC, dalonsod commented
Could you provide a screenshoot of some sales orders in the tree view with different invoice periods? I would like to see how badge widget is finally rendered

2024-11-20 15:32 UTC, DantePereyra commented
![imagen](https://github.com/user-attachments/assets/3e4fc04c-0646-4672-96d6-7b28875ab451)
There it is

2024-11-20 15:52 UTC, dalonsod commented
OK... could you add some colors to badges, so each value has a different color? `invoice_status` field view definition has the key of that IMO. I have no preferences about every color...

2024-11-20 16:43 UTC, DantePereyra commented
![imagen](https://github.com/user-attachments/assets/3f6074fe-1632-450a-bedf-1849c7a0fbd2)
Changes done.

2024-11-20 16:56 UTC, dalonsod requested changes
See minor comment, and I'll test it ASAP. Good work!

2024-11-20 16:56 UTC, dalonsod commented on sale_order_partner_invoice_period/i18n/es.po
> +msgstr "Diaria"
Period bad genre:
```suggestion
msgstr "Diario"
```

2024-11-20 16:58 UTC, DantePereyra commented
Perfect, done and ready! Thanks!

2024-11-21 11:53 UTC, DantePereyra commented
Changes done with new requirements.

2024-11-26 09:22 UTC, DantePereyra commented
Added the last requirements.

2025-10-21 16:09 UTC, dalonsod requested changes
See new comments

2025-10-21 16:09 UTC, dalonsod commented on sale_order_partner_invoice_period/models/sale_order.py
> +        store=True
This should be editable:
```suggestion
        store=True,
        readonly=False,
```

2025-10-21 16:09 UTC, dalonsod commented on sale_order_partner_invoice_period/readme/CONTRIBUTORS.rst
> +* Dante Pereyra <dante.pereyra@solvos.es>
Move these fields to `.md` extension & syntax

2025-10-22 16:09 UTC, dalonsod approved these changes
Good enough, let's merge!

2025-10-22 16:09 UTC, merged